### ISSUE TITLE
Farm : Smart Silo Routing

### ISSUE THREAD

**Issue by isontheline** [dRAGon-Okinawa/dRAGon#89]
- [x] FarmEntity : add setting enum => queryRouterType
  - [x] If queryRouterType is "default" : call each Silo + Granary
  - [x] If queryRouterType is "language model" : ask LLM to choose one or more Silo + Granary
  - [x] Use FallbackStrategy => retrieve on all? Or none?
- [x] SiloEntity + GranaryEntity : add String field "description" => mandatory or not?
  - [x] Description will be used in order to help the LLM to choose the best ones
- [x] Use langchain4j "LanguageModelQueryRouter" => choose one or more Silos / Granaries to retrieve

**Comment by amengus87** [comment]
Closed by https://github.com/dRAGon-Okinawa/dRAGon/pull/283
